version: '3'
services:
  postgres:
    image: 'postgres:alpine'
    volumes:
      - ./sql/create_schema_de_test.sql:/docker-entrypoint-initdb.d/create_schema_de_test.sql
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: conta